# Изключения

Събитие (проблем), което се случва по време на изпълнение на дадена програма и нарушава нормалната последователност на изпълнение на инструкциите ѝ. Още един начин за комуникация на метод с извикващите го: връщана стойност при нормално изпълнение и изключение при проблем.

Изключения възникват при:

- Подаване на невалидни входни данни
- Опитваме се да отворим несъществуващ файл
- Мрежата се е разкачила по време на комуникация
- Свършила е паметта на виртуалната машина
- и др.

## Видове изключения

Изключителните събития могат да се дължат на грешка на потребителя, бъг в кода или физически ресурс, който не е достъпен. Делят се на три вида:

- **Checked (Compile-time) exceptions** - Наричат се още compile-time exceptions, защото компилаторът ни задължава да ги обработим. Едно добре написано приложение би трябвало да ги очаква и да се възстановява от тях

**пример** 
- ```FileNotFoundException``` - при опит да отворим файл, какъвто не съществува
- ```IOException``` - при проблем за четене или писане във файл

- **Unchecked (Runtime) exceptions** - Възникват по време на изпълнение на приложението, затова се наричат още runtime exceptions. Приложението обикновено не може да ги очаква или да се възстанови от тях. Най-често са резултат от бъгове (логически грешки) в кода, неправилно извикване на API-та и т.н.

**пример**
- ```ArithmeticException```- при опит за деление на нула
- ```ArrayIndexOutOfBoundsException``` - при опит да достъпим елемент на масив по индекс извън размера на масива
- ```NullPointerException``` - при опит за достъпване на член-данна или метод на обект по референция, която е null
- ```ClassCastException``` - при опит да се cast-не обект към клас, на който обектът не е инстанция

- **Errors** - Проблеми, които възникват извън приложението, и приложението обикновено не може да ги очаква или да се възстанови след тях. Обикновено се генерират от самата виртуална машина.

**пример**
- ```OutOfMemoryError``` - при опит да заделим памет, когато свободната памет не е достатъчна (и не може да освободи с garbage collection).
- ```StackOverflowError``` - когато метод извиква свое копие твърде много пъти (напр. при безкрайна рекурсия)

## Генериране/хвърляне на изключение

става с ключовата дума ```throw```

**пример**

- Хвърляне на изключение в тяло на метод
```java
public Object pop() {
    if (size == 0) {
        throw new EmptyStackException();
    }
    // [...]
}
```

- Хвърляне на изключение в сигнатура на метод
```java
public void writeList() throws IOException, FileNotFoundException {
    // [...]
}
```

## Обработване на изключение

- пълен синтаксис
```java
try {
    // код, който може да хвърли изключение
} catch (Exception e) {
    // обработваме изключението ("exception handler")
    // може да има повече от един catch блок
} finally {
    // при нужда, някакви заключителни операции
    // finally блокът е optional, но ако го има,
    // се изпълнява задължително щом влезем в try-a
}
```

- синтаксис с множество catch блокове
```java
try { 
    // [...]
} catch (MostSpecificException mse) {
    // [...]
} catch (MoreGeneralException mge) {
    // [...]
} ... {
    // [...]
} catch (LeastSpecificException lse) {
    // [...]
}
```

- синтаксис с един catch блок и множество изключения
```java
try {
    // [...]
} catch (IOException | SQLException e) {
    // [...]
}
``` 

**пример**

```java
try {
    // [...]
} catch (IOException e) {
    // прехващаме изключение, обработваме го 
    // и хвърляме ново, към което го "закачаме"
    throw new SampleException("Oopss..", e); 
}
```

# Finally – не само за обработка на изключения

```java
try { 
    // тук може да се хвърлят изключения
    // или да има return/continue/break
} finally {
    // някакъв важен cleanup code -
    // ще се изпълни винаги*, независимо какво се случи в try блока
}
```

### ВАЖНО
Изключенията позволяват да се обработват грешки, отделно от останалия код. Това прави програмата лесно четима. Позволява "Препредаване" на грешки по стека на извикванията. Групиране и разграничаване на различните типове грешки.с